### ISSUE TITLE
79 Leetcode | Word Search

### ISSUE THREAD

**Issue by brijeshrakholia** [brijeshrakholia/daily_questions#2]
Given a 2D board and a word, find if the word exists in the grid.

The word can be constructed from letters of sequentially adjacent cell, where "adjacent" cells are those horizontally or vertically neighboring. The same letter cell may not be used more than once.

For example,
Given board =
```
[
  ['A','B','C','E'],
  ['S','F','C','S'],
  ['A','D','E','E']
]
```

word = `"ABCCED"`, -> returns `true`,
word = `"SEE"`, -> returns `true`,
word = `"ABCB"`, -> returns `false`.

**Comment by zmwieand** [comment]
* DFS seems to be the approach
* How to mark letters as visited?
