### ISSUE TITLE
415 Leetcode | Add Strings

### ISSUE THREAD

**Issue by brijeshrakholia** [brijeshrakholia/daily_questions#5]
Given two non-negative numbers num1 and num2 represented as string, return the sum of num1 and num2.

Note:
- The length of both num1 and num2 is < 5100.
- Both num1 and num2 contains only digits 0-9.
- Both num1 and num2 does not contain any leading zero.
- You must not use any built-in BigInteger library or convert the inputs to integer directly.

**Comment by zmwieand** [comment]
Should the output be a `string` or `int`?

**Comment by brijeshrakholia** [comment]
string
